//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingLogs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"C:\Projects\github\tys-hiroshi\storage\OrgLogs\WebAppLogs\204,C:\Projects\github\tys-hiroshi\storage\OrgLogs\WebAppLogs\206,C:\Projects\github\tys-hiroshi\storage\OrgLogs\WebAppLogs\162,C:\Projects\github\tys-hiroshi\storage\OrgLogs\WebAppLogs\163,C:\Projects\github\tys-hiroshi\storage\OrgLogs\WebAppLogs\165,C:\Projects\github\tys-hiroshi\storage\OrgLogs\WebAppLogs\166")]
        public string WebAppOrgLogDirPaths {
            get {
                return ((string)(this["WebAppOrgLogDirPaths"]));
            }
            set {
                this["WebAppOrgLogDirPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"C:\Projects\github\tys-hiroshi\storage\Logs\WebAppLogs\204,C:\Projects\github\tys-hiroshi\storage\Logs\WebAppLogs\206,C:\Projects\github\tys-hiroshi\storage\Logs\WebAppLogs\162,C:\Projects\github\tys-hiroshi\storage\Logs\WebAppLogs\163,C:\Projects\github\tys-hiroshi\storage\Logs\WebAppLogs\165,C:\Projects\github\tys-hiroshi\storage\Logs\WebAppLogs\166")]
        public string WebAppLogDirPaths {
            get {
                return ((string)(this["WebAppLogDirPaths"]));
            }
            set {
                this["WebAppLogDirPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("タイムアウト,timeout,デッドロック")]
        public string SearchWords {
            get {
                return ((string)(this["SearchWords"]));
            }
            set {
                this["SearchWords"] = value;
            }
        }
    }
}
